#!/usr/bin/env python3
"""
按教材18章原文（/Users/zhangxiaoyuan/Desktop/agent_teacher/教材/*.docx）手写生成的题库，
不是模型脱离原文自由发挥——每道题都能在对应章节的docx原文里找到依据，题干/选项措辞做了
改写（不是原文照抄），但考点和正确答案都锚定在原文陈述上，降低"专业内容编错"的风险。

字段结构与 题库/parse_question_bank.py 解析出的 题库.json 完全一致，方便后续合并使用，
唯一区别是 source 统一写成 "ai-gen"，跟人工导入的题库区分开来源。

运行： python3 generate_ai_questions.py
输出： AI生成题库.json
"""

import json
import os

OUTPUT_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), "AI生成题库.json")
SOURCE_LABEL = "ai-gen"


def q(type_, stem, answer, kp, difficulty="中", options=None, explanation=""):
    return {
        "type": type_,
        "stem": stem,
        "stem_images": [],
        "options": options or [],
        "answer": answer,
        "explanation": explanation,
        "difficulty": difficulty,
        "knowledge_point_id": kp,
        "source": SOURCE_LABEL,
    }


def opts(*pairs):
    return [{"label": l, "text": t} for l, t in pairs]


QUESTIONS = [
    # ================= 第一章：机器的组成 =================
    q("single_choice", "机械系统中，用来向机器提供运动和动力的部分称为____。", "B", "machine_composition",
      options=opts(("A", "执行系统"), ("B", "动力系统"), ("C", "传动系统"), ("D", "控制系统")),
      explanation="动力系统包括原动机及其配套装置，是机械系统的动力源。"),
    q("single_choice", "直接与工作对象接触、完成机器预期功能的部分是____。", "C", "machine_composition",
      options=opts(("A", "传动系统"), ("B", "控制系统"), ("C", "执行系统"), ("D", "辅助系统"))),
    q("true_false", "一部机器只能有一个执行机构，不能分解成多个执行机构。", False, "machine_composition",
      explanation="一部机器可以只有一个执行机构，也可以把功能分解成几个执行机构。"),
    q("fill_blank", "机械系统一般由动力系统、____、传动系统、控制系统和辅助系统组成。", ["执行系统"], "machine_composition"),
    q("multiple_choice", "下列属于常用原动机的是____。", ["A", "B", "C", "D"], "machine_composition",
      options=opts(("A", "电动机"), ("B", "内燃机"), ("C", "液压马达"), ("D", "气马达"))),
    q("single_choice", "传动系统的主要功能是____。", "D", "machine_composition",
      options=opts(("A", "提供机器的动力"), ("B", "协调各系统动作"), ("C", "完成显示、照明等辅助功能"),
                    ("D", "实现运动形式、运动及动力参数的转换"))),
    q("short_answer", "简述控制系统在机械系统中的作用。", "协调动力系统、执行系统和传动系统的动作，准确可靠地完成整部机器的功能。", "machine_composition"),
    q("fill_blank", "由凸轮、推杆和机架组成的凸轮机构，可将凸轮轴的转动变换为推杆的____运动。", ["上下直移"], "machine_composition"),
    q("fill_blank", "由两个齿轮和机架组成、用来传递两轴间运动和动力的机构称为____。", ["齿轮机构"], "machine_composition"),
    q("single_choice", "由滑块、连杆、曲柄、机架组成的连杆机构，其功能是将滑块的往复运动变换为曲柄的____运动。", "B", "machine_composition",
      options=opts(("A", "间歇"), ("B", "回转"), ("C", "摆动"), ("D", "振动"))),

    # ================= 第二章：平面机构的结构分析基础 =================
    q("single_choice", "平面机构自由度的计算公式为F=____。（n为活动构件数，PL为低副数，PH为高副数）", "A", "mechanism_dof",
      options=opts(("A", "3n-2PL-PH"), ("B", "3n-PL-2PH"), ("C", "2n-3PL-PH"), ("D", "3n-2PL+PH"))),
    q("true_false", "两个构件通过点、线接触构成的运动副称为低副。", False, "mechanism_dof",
      explanation="点、线接触构成的是高副；面接触构成的才是低副。"),
    q("single_choice", "两构件通过圆柱面接触，只允许两构件绕轴线相对转动，这种运动副称为____。", "B", "mechanism_dof",
      options=opts(("A", "移动副"), ("B", "转动副"), ("C", "高副"), ("D", "螺旋副"))),
    q("fill_blank", "机构具有确定运动的条件是机构的自由度必须____，且原动件数必须等于自由度。", ["大于零"], "mechanism_dof"),
    q("multiple_choice", "计算机构自由度时，需要在计算前排除（不计入自由度计算）的特殊情况是____。", ["B", "C"], "mechanism_dof",
      options=opts(("A", "复合铰链"), ("B", "局部自由度"), ("C", "虚约束"), ("D", "转动副")),
      explanation="局部自由度和虚约束要在计算前排除；复合铰链不是要排除的对象，而是计算低副数时容易漏数或多数，需要正确识别。"),
    q("single_choice", "与其他约束作用重复、对机构运动不起独立限制作用的约束称为____。", "C", "mechanism_dof",
      options=opts(("A", "复合铰链"), ("B", "局部自由度"), ("C", "虚约束"), ("D", "高副"))),
    q("single_choice", "两个以上构件在同一轴线上组成多个转动副，投影在运动平面上发生重叠，这种结构称为____。", "A", "mechanism_dof",
      options=opts(("A", "复合铰链"), ("B", "虚约束"), ("C", "局部自由度"), ("D", "运动链"))),
    q("single_choice", "两构件相对运动时，绝对速度相等、相对速度为零的瞬时重合点称为____。", "B", "instant_center",
      options=opts(("A", "转动中心"), ("B", "速度瞬心"), ("C", "质心"), ("D", "回转中心"))),
    q("true_false", "若两个构件都是活动构件，则它们之间的瞬心称为绝对瞬心。", False, "instant_center",
      explanation="两构件都是活动构件时称为相对瞬心；其中一个是机架时，该瞬心才称为绝对瞬心。"),
    q("fill_blank", "若两构件中有一个为机架，则它们的瞬心称为____瞬心。", ["绝对"], "instant_center"),
    q("single_choice", "机构组成的两个基本要素是____。", "B", "mechanism_dof",
      options=opts(("A", "构件和零件"), ("B", "构件和运动副"), ("C", "运动副和运动链"), ("D", "机架和原动件"))),
    q("single_choice", "平面高副允许两构件沿公切线相对移动的同时，还允许两构件____。", "A", "mechanism_dof",
      options=opts(("A", "绕过接触点且垂直t-n平面的轴相对转动"), ("B", "沿公法线方向移动"),
                    ("C", "绕z轴任意转动"), ("D", "沿任意方向移动"))),
    q("true_false", "机架是机构中相对固定不动的构件，是研究其他构件运动的参考坐标系。", True, "mechanism_dof"),
    q("fill_blank", "机构中由外界施加驱动力（或驱动力矩）、且运动规律已知的构件称为____。", ["原动件"], "mechanism_dof"),
    q("single_choice", "平面机构中活动构件数n与机构构件总数N的关系是____。", "B", "mechanism_dof",
      options=opts(("A", "n=N"), ("B", "n=N-1"), ("C", "n=N+1"), ("D", "n=2N")),
      explanation="机架固定不动、自由度为零，活动构件数n=N-1。"),

    # ================= 第三章：平面连杆机构 =================
    q("single_choice", "铰链四杆机构中，若两连架杆一个为曲柄、另一个为摇杆，该机构称为____。", "C", "lever_condition",
      options=opts(("A", "双曲柄机构"), ("B", "双摇杆机构"), ("C", "曲柄摇杆机构"), ("D", "曲柄滑块机构"))),
    q("true_false", "双曲柄机构中，若相对两杆平行且长度相等（平行四边形机构），主动曲柄和从动曲柄的角速度大小相等。", True, "lever_condition",
      explanation="平行四边形机构的特点是两曲柄以相同的角速度同向转动，连杆作平动。"),
    q("fill_blank", "铰链四杆机构存在曲柄的条件是：满足杆长条件，且以____为连架杆或机架。", ["最短杆"], "lever_condition"),
    q("single_choice", "曲柄与连杆两次共线位置之间所夹的锐角称为____。", "C", "dead_point_quick_return",
      options=opts(("A", "传动角"), ("B", "压力角"), ("C", "极位夹角"), ("D", "摆角"))),
    q("true_false", "极位夹角为0°时，机构的行程速比系数K=1，机构具有明显的急回特性。", False, "dead_point_quick_return",
      explanation="极位夹角为0°时K=1，此时机构无急回运动特性，而不是具有明显急回特性。"),
    q("single_choice", "机构的压力角为90°（传动角为0°）时，机构所处的位置称为____。", "A", "pressure_angle",
      options=opts(("A", "死点位置"), ("B", "平衡位置"), ("C", "极限位置"), ("D", "啮合位置"))),
    q("single_choice", "平面连杆机构又称为____机构。", "B", "lever_condition",
      options=opts(("A", "高副"), ("B", "低副"), ("C", "凸轮"), ("D", "齿轮"))),
    q("single_choice", "平面四杆机构的基本型式是____。", "B", "lever_condition",
      options=opts(("A", "曲柄滑块机构"), ("B", "铰链四杆机构"), ("C", "凸轮机构"), ("D", "齿轮机构"))),
    q("true_false", "双摇杆机构中，两个连架杆都是摇杆。", True, "lever_condition"),
    q("fill_blank", "若满足杆长条件但以最短杆作为连杆（不与机架相邻），则机构类型为____机构。", ["双摇杆"], "lever_condition"),
    q("single_choice", "若不满足杆长条件，无论哪个杆作机架，铰链四杆机构只能获得____。", "C", "lever_condition",
      options=opts(("A", "曲柄摇杆机构"), ("B", "双曲柄机构"), ("C", "双摇杆机构"), ("D", "曲柄滑块机构"))),
    q("multiple_choice", "机构具有急回运动的条件包括____。", ["A", "B", "C"], "dead_point_quick_return",
      options=opts(("A", "原动件作等速整周回转运动"), ("B", "输出件作往返两行程的运动"),
                    ("C", "极位夹角大于0°"), ("D", "机架必须是最短杆"))),
    q("single_choice", "压力角与传动角的关系是____。", "B", "pressure_angle",
      options=opts(("A", "两者相等"), ("B", "两者互余（之和为90°）"), ("C", "两者互补（之和为180°）"), ("D", "无固定关系"))),
    q("true_false", "压力角越小，传动角越大，机构的传力性能越好。", True, "pressure_angle"),

    # ================= 第四章：凸轮机构 =================
    q("single_choice", "凸轮机构由凸轮、从动件和____三个基本构件组成。", "B", "cam_mechanism",
      options=opts(("A", "连杆"), ("B", "机架"), ("C", "滑块"), ("D", "齿轮"))),
    q("true_false", "凸轮机构属于低副机构。", False, "cam_mechanism", explanation="凸轮廓线与从动件之间是点、线接触，属于高副机构。"),
    q("fill_blank", "为避免运动失真，应使凸轮理论廓线的最小曲率半径大于____。", ["滚子半径"], "cam_mechanism"),
    q("single_choice", "凸轮机构回程通常比推程可以采用更大许用压力角，主要原因是____。", "B", "cam_mechanism",
      options=opts(("A", "回程速度更快"), ("B", "力锁合凸轮机构回程时封闭力较小、一般无自锁问题"),
                    ("C", "回程从动件质量更大"), ("D", "回程凸轮转速更低"))),
    q("single_choice", "从动件在运动开始和终止时加速度理论上发生无穷大突变的运动规律，会引起____。", "B", "cam_motion_law",
      options=opts(("A", "柔性冲击"), ("B", "刚性冲击"), ("C", "无冲击"), ("D", "接触疲劳"))),
    q("fill_blank", "从动件运动规律中，加速度对时间的导数称为____。", ["跃度"], "cam_motion_law"),
    q("single_choice", "凸轮机构的优点不包括____。", "D", "cam_mechanism",
      options=opts(("A", "结构简单紧凑"), ("B", "工作可靠"), ("C", "可实现各种预期运动规律"), ("D", "凸轮与从动件之间摩擦磨损小")),
      explanation="凸轮廓线与从动件是高副接触，恰恰容易磨损，这是凸轮机构的缺点而非优点。"),
    q("true_false", "凸轮机构一般用于传力较大、位移较大的场合。", False, "cam_mechanism",
      explanation="凸轮机构一般多用于传力不大、位移不大的场合。"),
    q("fill_blank", "凸轮机构中，从动件位移、速度、加速度、跃度随时间变化的规律，又称从动件____线图。", ["运动"], "cam_motion_law"),
    q("single_choice", "直动滚子从动件盘形凸轮机构的压力角，是指凸轮廓线法线与从动件____之间的夹角。", "A", "cam_mechanism",
      options=opts(("A", "运动方向线"), ("B", "回转轴线"), ("C", "对称轴线"), ("D", "基圆切线"))),
    q("single_choice", "对于形锁合的凸轮机构，回程许用压力角一般____推程时的数值。", "B", "cam_mechanism",
      options=opts(("A", "大于"), ("B", "仍取（与之相当）"), ("C", "小于"), ("D", "无法确定"))),
    q("fill_blank", "凸轮机构设计中，滚子半径rr通常取基圆半径r0的____倍范围内选取。", ["0.1~0.5"], "cam_mechanism"),

    # ================= 第五章：齿轮传动 =================
    q("single_choice", "渐开线齿轮传动的中心距在一定范围内变化时，其传动比____。", "C", "gear_involute",
      options=opts(("A", "随之增大"), ("B", "随之减小"), ("C", "保持不变"), ("D", "无法确定")),
      explanation="这是渐开线齿轮传动的中心距可分性。"),
    q("true_false", "渐开线齿廓在传动过程中，齿廓间正压力的方向始终不变。", True, "gear_involute"),
    q("fill_blank", "齿轮分度圆上的压力角，国家标准规定为____度。", ["20"], "gear_involute"),
    q("single_choice", "两齿廓啮合传动时，啮合角的大小随____变化。", "B", "gear_involute",
      options=opts(("A", "齿轮转速"), ("B", "中心距"), ("C", "齿轮材料"), ("D", "润滑条件"))),
    q("single_choice", "下列不属于标准齿轮判定条件的是____。", "D", "gear_profile_shift",
      options=opts(("A", "分度圆上具有标准模数和标准压力角"), ("B", "分度圆上齿厚等于齿槽宽"),
                    ("C", "具有标准的齿顶高和齿根高"), ("D", "齿数必须大于100"))),
    q("true_false", "用范成法加工标准齿轮时，齿数过少会发生根切现象。", True, "gear_profile_shift"),
    q("multiple_choice", "避免齿轮根切现象的方法有____。", ["A", "B", "C"], "gear_profile_shift",
      options=opts(("A", "减小齿顶高系数"), ("B", "增大压力角"), ("C", "采用变位修正法（刀具外移）"), ("D", "增大模数"))),
    q("single_choice", "斜齿轮的法面参数取为标准值，主要原因是____。", "B", "gear_helical_bevel",
      options=opts(("A", "法面上轮齿受力更均匀"), ("B", "加工时刀具通常沿螺旋线方向（法面方向）进刀"),
                    ("C", "法面上的圆是分度圆"), ("D", "国家标准只规定了法面参数"))),
    q("single_choice", "蜗杆传动的正确啮合条件是：蜗杆轴面的模数和压力角分别等于蜗轮____的模数和压力角。", "B", "worm_gear",
      options=opts(("A", "法面"), ("B", "端面"), ("C", "轴面"), ("D", "螺旋面"))),
    q("true_false", "蜗杆头数越多，越容易实现自锁。", False, "worm_gear", explanation="蜗杆头数越少越容易自锁，头数越多传动效率越高但自锁性变差。"),
    q("single_choice", "齿轮传动的平均传动比总是等于两齿轮____的反比。", "B", "gear_involute",
      options=opts(("A", "分度圆直径"), ("B", "齿数"), ("C", "模数"), ("D", "压力角"))),
    q("single_choice", "两基圆的内公切线N1N2线，其含义不包括____。", "D", "gear_involute",
      options=opts(("A", "两齿廓在啮合点的公法线"), ("B", "啮合线"), ("C", "不计摩擦时两齿廓间的力作用线"), ("D", "分度圆的公切线"))),
    q("true_false", "啮合角随中心距的变化而变化，中心距越大，啮合角越大。", True, "gear_involute"),
    q("fill_blank", "一个齿槽两侧齿廓间的弧线长度称为该圆上的____。", ["齿槽宽"], "gear_profile_shift"),
    q("single_choice", "模数是分度圆____与π的比值。", "C", "gear_profile_shift",
      options=opts(("A", "直径"), ("B", "半径"), ("C", "齿距"), ("D", "齿厚"))),
    q("true_false", "模数越大，齿轮的齿距、齿厚、轮齿尺寸都越大。", True, "gear_profile_shift"),
    q("single_choice", "齿轮径向间隙（顶隙）存在的作用是____。", "B", "gear_profile_shift",
      options=opts(("A", "减小齿轮体积"), ("B", "便于储存润滑油、避免两齿轮卡死"), ("C", "增大传动比"), ("D", "减小根切"))),
    q("true_false", "齿侧间隙的存在有利于提高齿轮传动的运动精度。", False, "gear_involute",
      explanation="侧隙存在会产生换向冲击和回差，对运动精度要求高的仪器仪表反而不利，侧隙只能很小，设计仍按无侧隙进行。"),
    q("single_choice", "目前齿轮加工中应用最广泛的方法是____。", "B", "gear_profile_shift",
      options=opts(("A", "仿形法"), ("B", "范成法"), ("C", "铸造法"), ("D", "冲压法"))),
    q("single_choice", "蜗杆头数z1=1时称为____。", "A", "worm_gear",
      options=opts(("A", "单头蜗杆"), ("B", "双头蜗杆"), ("C", "多头蜗杆"), ("D", "标准蜗杆"))),
    q("single_choice", "当蜗杆导程角小于当量摩擦角时，蜗杆蜗轮机构具有____。", "B", "worm_gear",
      options=opts(("A", "高效率"), ("B", "自锁性"), ("C", "大传动比"), ("D", "低噪声"))),

    # ================= 第六章：轮系 =================
    q("single_choice", "运转时所有齿轮几何轴线相对机架位置都固定不变的轮系称为____。", "B", "gear_train",
      options=opts(("A", "周转轮系"), ("B", "定轴轮系"), ("C", "复合轮系"), ("D", "行星轮系"))),
    q("single_choice", "划分复合轮系中的基本周转轮系时，应首先找出____。", "C", "gear_train",
      options=opts(("A", "定轴齿轮"), ("B", "系杆"), ("C", "行星轮"), ("D", "中心轮")),
      explanation="正确顺序是先找行星轮，再找支承它的系杆，再找与系杆同轴线且与行星轮啮合的中心轮。"),
    q("true_false", "计算复合轮系传动比时，可以把整个复合轮系当作一个周转轮系，直接用转化机构法求解。", False, "gear_train",
      explanation="必须先正确区分各个基本轮系，分别列出传动比方程，建立联系后再联立求解。"),
    q("multiple_choice", "确定行星轮系齿数时必须满足的条件包括____。", ["A", "B", "C", "D"], "gear_train",
      options=opts(("A", "传动比条件"), ("B", "同心条件"), ("C", "装配条件"), ("D", "邻接条件"))),
    q("fill_blank", "周转轮系的结构特点是至少有一个齿轮的轴线绕另一固定轴线转动，这个齿轮称为____。", ["行星轮"], "gear_train"),
    q("single_choice", "轮系传动比的大小等于____角速度（或转速）之比。", "A", "gear_train",
      options=opts(("A", "输入轴与输出轴"), ("B", "主动轮与从动轮"), ("C", "系杆与行星轮"), ("D", "两个中心轮"))),
    q("true_false", "复合轮系是既包含定轴轮系部分又包含周转轮系部分，或由几个基本周转轮系组成的轮系。", True, "gear_train"),
    q("fill_blank", "划分基本轮系后，剩下由定轴齿轮组成的部分就是____轮系。", ["定轴"], "gear_train"),
    q("single_choice", "行星轮系采用多个均匀分布的行星轮，其目的不包括____。", "D", "gear_train",
      options=opts(("A", "提高承载能力"), ("B", "使中心轮上合力为零"), ("C", "平衡系杆所受离心惯性力"), ("D", "减少行星轮齿数"))),
    q("single_choice", "为保证相邻两行星轮不发生碰撞干涉，需满足的条件称为____。", "C", "gear_train",
      options=opts(("A", "同心条件"), ("B", "装配条件"), ("C", "邻接条件"), ("D", "传动比条件"))),
    q("true_false", "行星轮系的基本构件回转轴线必须重合于同一轴线，这称为同心条件。", True, "gear_train"),
    q("fill_blank", "复合轮系传动比计算的第一步是正确区分____。", ["各个基本轮系"], "gear_train"),

    # ================= 第七章：间歇运动机构 =================
    q("single_choice", "槽轮机构在起动和停止时具有的冲击类型是____。", "B", "intermittent_motion",
      options=opts(("A", "刚性冲击"), ("B", "柔性冲击"), ("C", "无冲击"), ("D", "周期性冲击"))),
    q("single_choice", "不完全齿轮机构进入和退出啮合时速度有突变，会引起____。", "B", "intermittent_motion",
      options=opts(("A", "柔性冲击"), ("B", "刚性冲击"), ("C", "弹性变形"), ("D", "噪声降低"))),
    q("true_false", "棘轮机构靠止动棘爪阻止棘轮反转，从而实现单向间歇运动。", True, "intermittent_motion"),
    q("fill_blank", "槽轮机构由主动拨盘、____和机架组成。", ["槽轮"], "intermittent_motion"),
    q("single_choice", "三种间歇运动机构中，转角大小不能调节、但机械效率高、能准确控制转角的是____。", "B", "intermittent_motion",
      options=opts(("A", "棘轮机构"), ("B", "槽轮机构"), ("C", "不完全齿轮机构"), ("D", "凸轮机构"))),
    q("single_choice", "槽轮机构中，当圆销未进入径向槽时，槽轮靠____保持静止。", "B", "intermittent_motion",
      options=opts(("A", "弹簧压紧"), ("B", "内凹锁止弧被外凸锁止弧锁住"), ("C", "摩擦力"), ("D", "止动棘爪"))),
    q("true_false", "不完全齿轮机构的从动轮轮齿布满整个圆周。", False, "intermittent_motion",
      explanation="不完全齿轮机构的轮齿不是布满整个圆周，这正是它区别于普通齿轮的地方。"),
    q("single_choice", "不完全齿轮机构的优点是____。", "B", "intermittent_motion",
      options=opts(("A", "无冲击"), ("B", "运动/静止时间比例可在较大范围内变化"), ("C", "适用于高速场合"), ("D", "转角可连续无级调节"))),
    q("fill_blank", "棘轮机构中，主动杆往复摆动时，靠驱动棘爪和____棘爪配合实现单向间歇运动。", ["止动"], "intermittent_motion"),

    # ================= 第八章：机械动力学基础 =================
    q("single_choice", "质心在回转轴线上，但各偏心质量不在同一回转平面内，这种不平衡现象称为____。", "B", "balance_and_flywheel",
      options=opts(("A", "静不平衡"), ("B", "动不平衡"), ("C", "完全平衡"), ("D", "局部不平衡"))),
    q("true_false", "静不平衡现象只有在转子转动时才能表现出来，静止时无法测出。", False, "balance_and_flywheel",
      explanation="静不平衡在静态即可测出，动不平衡才只有在转动时才显示出来。"),
    q("single_choice", "宽径比b/D≤0.2的转子，其质量可近似认为分布在____。", "B", "balance_and_flywheel",
      options=opts(("A", "通过质心的轴线上"), ("B", "垂直于回转轴线的同一平面内"),
                    ("C", "整个转子长度上均匀分布"), ("D", "回转轴线上"))),
    q("fill_blank", "弹簧的弹性力属于工作阻力是____的函数这一类机械特性。", ["位置"], "balance_and_flywheel"),
    q("multiple_choice", "下列属于工作阻力机械特性分类的是____。", ["A", "B", "C", "D"], "balance_and_flywheel",
      options=opts(("A", "常数"), ("B", "位置的函数"), ("C", "速度的函数"), ("D", "时间的函数"))),
    q("single_choice", "机械运转时忽略摩擦力，外力可分为驱动力和____两类。", "B", "balance_and_flywheel",
      options=opts(("A", "惯性力"), ("B", "工作阻力"), ("C", "约束力"), ("D", "离心力"))),
    q("true_false", "驱动力一般由原动机提供，各种原动机具有不同的机械特性。", True, "balance_and_flywheel"),
    q("single_choice", "揉面机随加工时间增加、面粉粘度增大而工作阻力增大，这属于工作阻力是____的函数。", "C", "balance_and_flywheel",
      options=opts(("A", "位置"), ("B", "速度"), ("C", "时间"), ("D", "常数"))),
    q("single_choice", "机械中离心惯性力产生的根本原因是____。", "B", "balance_and_flywheel",
      options=opts(("A", "构件材质不均匀"), ("B", "质心与回转轴线不重合"), ("C", "转速过高"), ("D", "润滑不良")),
      explanation="结构不对称、加工装配误差、材质不均匀等都是导致质心与回转轴线不重合的具体原因，但产生离心惯性力的直接根源是质心与回转轴线不重合。"),
    q("true_false", "离心惯性力呈周期性变化，可能引起机械及其基础产生强迫振动甚至共振。", True, "balance_and_flywheel"),

    # ================= 第九章：机械零件设计总论 =================
    q("single_choice", "机械零件最基本的设计准则是____。", "B", "fatigue_strength",
      options=opts(("A", "刚度准则"), ("B", "强度准则"), ("C", "耐磨性准则"), ("D", "振动稳定性准则"))),
    q("true_false", "疲劳断裂时零件所受的最大应力通常远比材料的强度极限低，甚至比屈服极限低。", True, "fatigue_strength"),
    q("single_choice", "疲劳断裂过程的第一阶段是____。", "C", "fatigue_strength",
      options=opts(("A", "裂纹扩展"), ("B", "剩余截面断裂"), ("C", "表面产生初始微裂纹"), ("D", "整体塑性变形"))),
    q("fill_blank", "疲劳断口的特征是无明显塑性变形的____突然断裂。", ["脆性"], "fatigue_strength"),
    q("multiple_choice", "机械零件的四大设计准则包括____。", ["A", "B", "C", "D"], "fatigue_strength",
      options=opts(("A", "强度准则"), ("B", "刚度准则"), ("C", "耐磨性准则"), ("D", "振动稳定性准则"))),
    q("single_choice", "计算载荷等于____与名义载荷的乘积。", "B", "fatigue_strength",
      options=opts(("A", "安全系数"), ("B", "载荷系数"), ("C", "许用应力"), ("D", "疲劳极限"))),
    q("single_choice", "下列不属于机械零件表面失效的是____。", "D", "fatigue_strength",
      options=opts(("A", "腐蚀"), ("B", "磨损"), ("C", "接触疲劳磨损"), ("D", "整体断裂")),
      explanation="整体断裂属于强度失效，不属于表面失效。"),
    q("single_choice", "磨粒磨损、粘着磨损（胶合）、接触疲劳磨损都属于____。", "B", "fatigue_strength",
      options=opts(("A", "腐蚀"), ("B", "磨损"), ("C", "整体断裂"), ("D", "残余变形"))),
    q("true_false", "刚度是指机械零件承受载荷时抵抗断裂或塑性变形的能力。", False, "fatigue_strength",
      explanation="这是强度的定义；刚度是指零件在载荷作用下抵抗弹性变形的能力。"),
    q("single_choice", "耐磨性准则是通过控制____来控制磨损量的大小。", "B", "fatigue_strength",
      options=opts(("A", "许用应力"), ("B", "单位面积上的压力"), ("C", "表面粗糙度"), ("D", "润滑油粘度"))),
    q("single_choice", "当零件工作频率等于或接近其固有频率时，会发生____。", "B", "fatigue_strength",
      options=opts(("A", "疲劳断裂"), ("B", "共振"), ("C", "腐蚀"), ("D", "胶合"))),
    q("fill_blank", "载荷按大小、方向是否随时间变化，可分为静载荷和____。", ["变载荷"], "fatigue_strength"),
    q("single_choice", "机械零件的设计计算一般按____进行。", "C", "fatigue_strength",
      options=opts(("A", "名义载荷"), ("B", "工作载荷"), ("C", "计算载荷"), ("D", "极限载荷"))),
    q("true_false", "静应力只能在静载荷作用下产生，变应力只能在变载荷作用下产生。", False, "fatigue_strength",
      explanation="变应力既可以在变载荷下产生，也可以在静载荷作用下产生（如旋转轴上的弯曲应力）。"),
    q("multiple_choice", "影响机械零件疲劳强度的最重要因素包括____。", ["A", "B", "C"], "fatigue_strength",
      options=opts(("A", "应力集中"), ("B", "零件尺寸"), ("C", "表面状态"), ("D", "零件颜色"))),
    q("single_choice", "疲劳断裂过程的第三阶段是____。", "C", "fatigue_strength",
      options=opts(("A", "产生初始微裂纹"), ("B", "裂纹反复塑性变形扩展"), ("C", "剩余截面静强度不足而断裂"), ("D", "表面腐蚀"))),

    # ================= 第十章：螺纹连接、键连接、销连接 =================
    q("single_choice", "需要预紧的螺纹连接称为____。", "B", "screw_bolt_connection",
      options=opts(("A", "松连接"), ("B", "紧连接"), ("C", "动连接"), ("D", "过渡连接"))),
    q("true_false", "摩擦防松比机械防松更可靠，应用更广泛。", False, "screw_bolt_connection",
      explanation="机械防松比摩擦防松更可靠、应用更广；摩擦防松不十分可靠，多用于冲击振动较小的场合。"),
    q("multiple_choice", "螺纹连接防松的方法按工作原理可分为____。", ["A", "B", "C"], "screw_bolt_connection",
      options=opts(("A", "摩擦防松"), ("B", "机械防松"), ("C", "永久防松"), ("D", "弹性防松"))),
    q("single_choice", "普通平键连接中，起工作面作用、传递转矩的是键的____。", "C", "key_spline_connection",
      options=opts(("A", "上表面"), ("B", "下表面"), ("C", "两侧面"), ("D", "端面"))),
    q("single_choice", "固定在轮毂上、随轴上零件一起沿轴作较大距离滑移的键是____。", "B", "key_spline_connection",
      options=opts(("A", "导向平键"), ("B", "滑键"), ("C", "半圆键"), ("D", "楔键"))),
    q("true_false", "圆锥销比圆柱销装拆更方便，多次装拆对连接精度影响较小，应用更广泛。", True, "key_spline_connection"),
    q("single_choice", "在圆柱体外表面形成的螺纹称为____。", "B", "screw_bolt_connection",
      options=opts(("A", "内螺纹"), ("B", "外螺纹"), ("C", "传动螺纹"), ("D", "左旋螺纹"))),
    q("single_choice", "螺纹按牙型分类，不包括____。", "D", "screw_bolt_connection",
      options=opts(("A", "三角形螺纹"), ("B", "矩形螺纹"), ("C", "梯形螺纹"), ("D", "圆形螺纹"))),
    q("true_false", "机械制造中一般采用右旋螺纹，只有特殊情况才采用左旋螺纹。", True, "screw_bolt_connection"),
    q("fill_blank", "通常规定，拧紧后螺栓的预紧应力不得超过其材料屈服极限的____％。", ["80"], "screw_bolt_connection"),
    q("single_choice", "永久防松的特点是____。", "B", "screw_bolt_connection",
      options=opts(("A", "可重复使用"), ("B", "不能重复使用"), ("C", "可靠性最低"), ("D", "仅用于振动小的场合"))),
    q("single_choice", "键连接中，靠键与键槽侧面挤压传递转矩，说明键的工作面是____。", "C", "key_spline_connection",
      options=opts(("A", "上表面"), ("B", "下表面"), ("C", "两个侧面"), ("D", "端面"))),
    q("true_false", "半圆键能绕其几何中心在键槽中摆动，以适应轮毂中键槽的斜度，常用于锥形轴端。", True, "key_spline_connection"),
    q("single_choice", "圆柱销利用微量过盈固定在销孔中，多次装拆后会导致____。", "B", "key_spline_connection",
      options=opts(("A", "紧固性和定位精度提高"), ("B", "紧固性和定位精度降低"), ("C", "没有影响"), ("D", "只影响外观"))),
    q("single_choice", "开口销常与____构成铰链连接，并可用作防松零件。", "C", "key_spline_connection",
      options=opts(("A", "圆柱销"), ("B", "圆锥销"), ("C", "销轴"), ("D", "平键"))),
    q("multiple_choice", "键按结构形式分类，包括____。", ["A", "B", "C", "D"], "key_spline_connection",
      options=opts(("A", "平键"), ("B", "半圆键"), ("C", "楔键"), ("D", "切向键"))),

    # ================= 第十一章：齿轮的强度与失效 =================
    q("single_choice", "在润滑良好的闭式软齿面齿轮传动中，最主要的失效形式是____。", "B", "gear_failure",
      options=opts(("A", "轮齿折断"), ("B", "齿面疲劳点蚀"), ("C", "齿面磨损"), ("D", "胶合"))),
    q("single_choice", "开式齿轮传动的主要失效形式是____。", "B", "gear_failure",
      options=opts(("A", "齿面点蚀"), ("B", "齿面磨损"), ("C", "胶合"), ("D", "塑性变形"))),
    q("true_false", "齿面疲劳点蚀首先出现在节线附近的齿面上。", True, "gear_failure"),
    q("single_choice", "胶合主要出现在____的闭式齿轮传动中。", "B", "gear_failure",
      options=opts(("A", "低速轻载"), ("B", "高速重载"), ("C", "低速重载"), ("D", "高速轻载"))),
    q("multiple_choice", "提高齿轮抗断齿能力的措施包括____。", ["A", "B", "C"], "gear_failure",
      options=opts(("A", "增大齿根过渡圆角半径"), ("B", "在齿根处喷丸强化"), ("C", "选用韧性好的材料"), ("D", "减小轴及支承的刚性"))),
    q("single_choice", "疲劳折断和过载折断相比，过载折断多发生于____。", "B", "gear_failure",
      options=opts(("A", "渗碳齿轮"), ("B", "铸铁齿轮、整体淬火齿轮"), ("C", "调质齿轮"), ("D", "表面淬火齿轮"))),
    q("true_false", "疲劳折断是由于齿轮长期重复受载、齿根弯曲应力超过许用弯曲应力，逐渐产生并扩展裂纹导致的。", True, "gear_failure"),
    q("single_choice", "齿面点蚀首先出现在节线附近，主要原因之一是____。", "B", "gear_failure",
      options=opts(("A", "节线处齿面硬度最低"), ("B", "节线处相对滑动速度小，不易形成润滑油膜"),
                    ("C", "节线处压力角最大"), ("D", "节线处模数最小"))),
    q("multiple_choice", "提高齿轮抗点蚀能力的措施包括____。", ["A", "B", "C"], "gear_failure",
      options=opts(("A", "提高齿面硬度、降低粗糙度"), ("B", "提高润滑油粘度"),
                    ("C", "采用正传动增大综合曲率半径"), ("D", "改用开式传动"))),
    q("single_choice", "磨粒磨损常出现在____齿轮传动中。", "B", "gear_failure",
      options=opts(("A", "闭式"), ("B", "开式"), ("C", "高速重载"), ("D", "低速轻载闭式"))),
    q("fill_blank", "齿轮胶合是由于齿面间压力大、速度高，摩擦功耗产生高温破坏____，使两齿面金属直接接触粘焊。", ["油膜"], "gear_failure"),
    q("single_choice", "齿面塑性变形容易发生在____的齿轮传动中。", "B", "gear_failure",
      options=opts(("A", "高速轻载"), ("B", "低速重载或频繁启动"), ("C", "闭式软齿面"), ("D", "开式高速"))),
    q("single_choice", "一般直齿圆柱齿轮的齿数比u不宜超过____。", "B", "gear_failure",
      options=opts(("A", "2"), ("B", "5"), ("C", "10"), ("D", "20"))),
    q("true_false", "对于闭式软齿面齿轮传动，为提高传动平稳性和降低齿高，可适当增大小齿轮齿数、相应减小模数。", True, "gear_failure"),

    # ================= 第十二章：蜗杆传动的强度设计 =================
    q("single_choice", "蜗杆蜗轮传动的失效多发生在____上。", "B", "worm_gear",
      options=opts(("A", "蜗杆"), ("B", "蜗轮"), ("C", "两者概率相等"), ("D", "轴承")),
      explanation="蜗杆螺旋齿的强度比蜗轮轮齿的强度高，所以失效多发生在蜗轮上。"),
    q("true_false", "蜗轮常采用青铜制造，是为了获得良好的减摩、耐磨和抗胶合性能。", True, "worm_gear"),
    q("single_choice", "蜗杆传动闭式设计中，除接触疲劳强度设计和弯曲疲劳强度校核外，还需要进行____。", "B", "worm_gear",
      options=opts(("A", "振动校核"), ("B", "热平衡计算"), ("C", "刚度校核"), ("D", "冲击校核")),
      explanation="蜗杆传动滑动速度大、发热量大，闭式传动需额外进行热平衡计算。"),
    q("single_choice", "蜗杆传动的受力分析中，作用在蜗杆和蜗轮上的三对分力彼此关系为____。", "B", "worm_gear",
      options=opts(("A", "大小相等，方向相同"), ("B", "大小相等，方向相反"), ("C", "大小不等，方向相反"), ("D", "无固定关系"))),
    q("single_choice", "蜗杆传动因齿面间相对滑动速度大，最容易导致的失效是____。", "A", "worm_gear",
      options=opts(("A", "胶合"), ("B", "过载折断"), ("C", "疲劳折断"), ("D", "塑性变形"))),
    q("true_false", "蜗杆一般采用碳素钢或合金钢制造并经淬火处理，以获得较高的齿面硬度。", True, "worm_gear"),
    q("single_choice", "开式蜗杆传动因磨损速度大于点蚀速度，设计时主要按____进行。", "B", "worm_gear",
      options=opts(("A", "接触疲劳强度设计"), ("B", "弯曲强度设计"), ("C", "热平衡计算"), ("D", "刚度设计"))),

    # ================= 第十三章：带传动与链传动 =================
    q("single_choice", "摩擦型带传动过载时会____，从而保护其他零件不受损坏。", "B", "belt_chain_friction_drive",
      options=opts(("A", "断裂"), ("B", "打滑"), ("C", "跳齿"), ("D", "卡死"))),
    q("single_choice", "链传动磨损后容易发生的失效现象是____。", "B", "belt_chain_friction_drive",
      options=opts(("A", "打滑"), ("B", "跳齿"), ("C", "弹性滑动"), ("D", "整体断裂"))),
    q("true_false", "链传动没有弹性滑动和打滑现象，能保持准确的平均传动比。", True, "belt_chain_friction_drive"),
    q("fill_blank", "带传动一般推荐带速v=____m/s为最佳带速区间。", ["20~25"], "belt_chain_friction_drive"),
    q("single_choice", "滚子链的磨损主要发生在____的接触面上。", "B", "belt_chain_friction_drive",
      options=opts(("A", "滚子和套筒"), ("B", "销轴和套筒"), ("C", "内链板和外链板"), ("D", "链轮和滚子"))),
    q("single_choice", "带传动分为摩擦型和____两类。", "B", "belt_chain_friction_drive",
      options=opts(("A", "链啮合型"), ("B", "啮合型"), ("C", "齿轮型"), ("D", "滚动型"))),
    q("multiple_choice", "摩擦型带传动的优点包括____。", ["A", "B", "C"], "belt_chain_friction_drive",
      options=opts(("A", "能缓冲吸振、传动平稳"), ("B", "过载打滑、保护其他零件"),
                    ("C", "结构简单、成本较低"), ("D", "瞬时传动比恒定"))),
    q("true_false", "带轮直径减小会增加带的弯曲应力，导致疲劳寿命降低。", True, "belt_chain_friction_drive"),
    q("single_choice", "传动比过大会导致带轮包角____，容易打滑。", "B", "belt_chain_friction_drive",
      options=opts(("A", "增大"), ("B", "减小"), ("C", "不变"), ("D", "先增大后减小"))),
    q("fill_blank", "带传动的传动比一般不超过____，推荐值为2~5。", ["7"], "belt_chain_friction_drive"),
    q("single_choice", "与摩擦型带传动相比，链传动的主要优点是____。", "B", "belt_chain_friction_drive",
      options=opts(("A", "过载保护能力强"), ("B", "无弹性滑动，能保持准确的平均传动比"),
                    ("C", "瞬时传动比恒定"), ("D", "可用于任意角度交错轴传动"))),
    q("true_false", "链传动只能用于两平行轴间的同向回转传动。", True, "belt_chain_friction_drive"),
    q("single_choice", "滚子链中，滚子和轮齿间主要发生____摩擦，可减轻齿廓磨损。", "B", "belt_chain_friction_drive",
      options=opts(("A", "滑动"), ("B", "滚动"), ("C", "混合"), ("D", "静止"))),
    q("single_choice", "内导板齿形链适用于____场合。", "B", "belt_chain_friction_drive",
      options=opts(("A", "低速轻载"), ("B", "高速及重载传动"), ("C", "链轮宽度很小"), ("D", "开式传动"))),
    q("fill_blank", "链条磨损导致链轮节圆增大，最终会产生____或脱链而使传动失效。", ["跳齿"], "belt_chain_friction_drive"),
    q("single_choice", "链传动的承载能力主要以____为依据。", "B", "belt_chain_friction_drive",
      options=opts(("A", "链轮的强度"), ("B", "链的强度和寿命"), ("C", "电机功率"), ("D", "润滑方式"))),

    # ================= 第十四章：轴的设计 =================
    q("single_choice", "转轴设计时，首先按____估算轴的直径。", "B", "shaft_design",
      options=opts(("A", "精确弯矩计算"), ("B", "扭转强度或经验公式"), ("C", "振动稳定性计算"), ("D", "刚度计算")),
      explanation="因为轴的结构尺寸未定前无法求出弯矩，所以先按扭转强度/经验公式估算直径，再做结构设计，最后精确校核。"),
    q("true_false", "应力集中是轴产生疲劳破坏的主要原因。", True, "shaft_design"),
    q("fill_blank", "曲轴常用于____式机械中，是内燃机等机器的专用零件。", ["往复"], "shaft_design"),
    q("single_choice", "通过碾压、喷丸对轴表面进行强化处理，可使轴表层产生____，从而提高抗疲劳能力。", "B", "shaft_design",
      options=opts(("A", "残余拉应力"), ("B", "预压应力"), ("C", "硬化层"), ("D", "氧化膜"))),
    q("single_choice", "根据受载荷性质不同，直轴可分为心轴、转轴和____三种。", "B", "shaft_design",
      options=opts(("A", "曲轴"), ("B", "传动轴"), ("C", "软轴"), ("D", "空心轴"))),
    q("true_false", "钢丝软轴不受空间限制，能将扭转或旋转运动灵活传到任何所需位置。", True, "shaft_design"),
    q("single_choice", "轴的结构设计不需要重点考虑的是____。", "D", "shaft_design",
      options=opts(("A", "便于加工、测量、装配和维修"), ("B", "减小应力集中"),
                    ("C", "采用键连接时键槽应设计在同一加工直线上"), ("D", "尽量增大轴的直径以提高安全性"))),
    q("multiple_choice", "轴的工作能力计算可能包括____。", ["A", "B", "C"], "shaft_design",
      options=opts(("A", "强度计算"), ("B", "刚度计算"), ("C", "振动稳定性计算"), ("D", "外观设计"))),
    q("fill_blank", "轴端、轴颈与轴肩过渡部分应加工出倒角或____，以减小应力集中、便于装配。", ["过渡圆角"], "shaft_design"),
    q("single_choice", "合金钢制作的轴相比碳钢，对应力集中____。", "B", "shaft_design",
      options=opts(("A", "更不敏感"), ("B", "更敏感"), ("C", "完全不敏感"), ("D", "敏感程度相同"))),

    # ================= 第十五章：滚动轴承 =================
    q("single_choice", "承受纯轴向载荷时，一般选用____。", "C", "rolling_bearing",
      options=opts(("A", "深沟球轴承"), ("B", "圆柱滚子轴承"), ("C", "推力轴承"), ("D", "滚针轴承"))),
    q("single_choice", "滚动轴承基本额定寿命对应的可靠度是____。", "C", "rolling_bearing",
      options=opts(("A", "100%"), ("B", "99%"), ("C", "90%"), ("D", "50%"))),
    q("true_false", "转速越高，滚动轴承润滑应选用粘度越高的润滑油。", False, "rolling_bearing",
      explanation="转速越高应选用粘度越低的润滑油；载荷越大才应选用粘度越高的润滑油。"),
    q("fill_blank", "衡量滚动轴承承载能力的主要指标是基本额定____。", ["动载荷"], "rolling_bearing"),
    q("single_choice", "对于转速很低、承受很大冲击载荷的轴承，主要采用的计算准则是____。", "B", "rolling_bearing",
      options=opts(("A", "寿命计算"), ("B", "静强度计算"), ("C", "极限转速校验"), ("D", "热平衡计算"))),
    q("single_choice", "转速较高、载荷较小、要求旋转精度较高时，宜选用____。", "B", "rolling_bearing",
      options=opts(("A", "滚子轴承"), ("B", "球轴承"), ("C", "推力轴承"), ("D", "滑动轴承"))),
    q("single_choice", "需要沿轴向安装和拆卸轴承，且轴承座不是剖分式时，宜优先选用____。", "B", "rolling_bearing",
      options=opts(("A", "深沟球轴承"), ("B", "内外圈可分离的轴承"), ("C", "调心球轴承"), ("D", "推力轴承"))),
    q("true_false", "保持架的主要作用是均匀隔开滚动体，避免相邻滚动体接触产生较大相对滑动而磨损。", True, "rolling_bearing"),
    q("fill_blank", "滚动体与外圈接触处法线与轴承径向平面之间的夹角称为轴承的____。", ["公称接触角"], "rolling_bearing"),
    q("multiple_choice", "与滑动轴承相比，滚动轴承的优点包括____。", ["A", "B", "D"], "rolling_bearing",
      options=opts(("A", "摩擦系数小，启动力矩小"), ("B", "属于标准件，互换性好"),
                    ("C", "抗冲击能力强"), ("D", "润滑简单，维护成本低")),
      explanation="滚动轴承的缺点恰恰是抗冲击能力较差，不能选C。"),
    q("true_false", "轴承基本额定寿命是以同批试验轴承中寿命最长的一个作为标准。", False, "rolling_bearing",
      explanation="基本额定寿命是10%轴承发生点蚀破坏前的转数（可靠度90%），不是取最长寿命。"),
    q("single_choice", "润滑脂的填充量一般以填充轴承和轴承壳体空间的____为宜。", "B", "rolling_bearing",
      options=opts(("A", "1/5到1/4"), ("B", "1/3到1/2"), ("C", "2/3到3/4"), ("D", "全部填满"))),
    q("single_choice", "载荷越大时，滚动轴承润滑应选用____的润滑油。", "B", "rolling_bearing",
      options=opts(("A", "粘度越低"), ("B", "粘度越高"), ("C", "与载荷无关"), ("D", "粘度适中固定值"))),

    # ================= 第十六章：滑动轴承 =================
    q("single_choice", "在所有轴承材料中，嵌入性及摩擦顺应性最好的是____。", "A", "sliding_bearing",
      options=opts(("A", "轴承合金"), ("B", "锡青铜"), ("C", "铝基轴承合金"), ("D", "粉末冶金材料"))),
    q("true_false", "轴承合金强度很高，可以单独制作整体轴瓦。", False, "sliding_bearing",
      explanation="轴承合金强度很低，不能单独制作轴瓦，只能贴附在青铜、钢或铸铁轴瓦上作轴承衬。"),
    q("single_choice", "材料通过表层弹塑性变形补偿轴颈挠曲和初始配合不良的能力称为____。", "C", "sliding_bearing",
      options=opts(("A", "嵌入性"), ("B", "磨合性"), ("C", "摩擦顺应性"), ("D", "减摩性"))),
    q("fill_blank", "多孔质金属材料轴承因孔隙中浸有润滑油、具有自润滑性，故称为____轴承。", ["含油"], "sliding_bearing"),
    q("single_choice", "轴颈与轴瓦直接接触时防止发生粘附和形成边界润滑的性能称为____。", "B", "sliding_bearing",
      options=opts(("A", "减摩性"), ("B", "摩擦相容性"), ("C", "嵌入性"), ("D", "磨合性"))),
    q("single_choice", "材料允许混入润滑剂中的硬质颗粒嵌入、防止刮伤或磨粒磨损的能力称为____。", "B", "sliding_bearing",
      options=opts(("A", "摩擦顺应性"), ("B", "嵌入性"), ("C", "磨合性"), ("D", "减摩性"))),
    q("true_false", "锡青铜的减摩性在铜合金中最好、应用较广，但硬度较高、磨合性及嵌入性较差。", True, "sliding_bearing"),
    q("single_choice", "适用于高速、重载轴承，抗粘附能力强的铜合金是____。", "B", "sliding_bearing",
      options=opts(("A", "锡青铜"), ("B", "铅青铜"), ("C", "铝青铜"), ("D", "黄铜"))),
    q("single_choice", "灰铸铁作为轴承材料的主要缺点是____。", "B", "sliding_bearing",
      options=opts(("A", "价格昂贵"), ("B", "性脆、磨合性差"), ("C", "导热性差"), ("D", "不能形成润滑层"))),
    q("fill_blank", "粉末冶金轴承材料的孔隙约占体积的____%~____%。", ["10", "35"], "sliding_bearing"),
    q("single_choice", "非金属轴承材料（如塑料）的主要缺点是____。", "C", "sliding_bearing",
      options=opts(("A", "减摩性差"), ("B", "耐磨性差"), ("C", "强度和导热性较差"), ("D", "耐腐蚀性差"))),
    q("single_choice", "润滑剂按物态可分为气体、液体、半固体和____四种基本类型。", "B", "sliding_bearing",
      options=opts(("A", "胶体"), ("B", "固体"), ("C", "混合态"), ("D", "等离子体"))),

    # ================= 第十七章：离合器 =================
    q("single_choice", "牙嵌式离合器和摩擦式离合器相比，具有过载打滑保护能力的是____。", "B", "clutch",
      options=opts(("A", "牙嵌式离合器"), ("B", "摩擦式离合器"), ("C", "两者都有"), ("D", "两者都没有"))),
    q("true_false", "梯形齿牙嵌式离合器能自行补偿磨损产生的间隙。", True, "clutch"),
    q("single_choice", "牙嵌式离合器牙形中，承载能力最大但仅能单向工作的是____。", "D", "clutch",
      options=opts(("A", "矩形齿"), ("B", "三角形齿"), ("C", "梯形齿"), ("D", "锯齿形"))),
    q("fill_blank", "离合器主要由主动部分、从动部分、接合部分和____组成。", ["操纵部分"], "clutch"),
    q("single_choice", "离合器按控制方式分类，能在特定工作条件下自动接合分离的是____。", "B", "clutch",
      options=opts(("A", "操纵式离合器"), ("B", "自动式离合器"), ("C", "机械式离合器"), ("D", "电磁式离合器"))),
    q("true_false", "矩形齿牙嵌式离合器磨损后间隙无法补偿，难以接合，只能用于静止状态下手动离合。", True, "clutch"),
    q("single_choice", "三角形齿牙嵌式离合器一般用于传递____转矩的低速离合器。", "B", "clutch",
      options=opts(("A", "大"), ("B", "小"), ("C", "中等"), ("D", "不确定"))),
    q("single_choice", "电磁牙嵌离合器通常采用嵌入方便的____细牙，便于遥控和程序控制。", "B", "clutch",
      options=opts(("A", "矩形"), ("B", "三角形"), ("C", "梯形"), ("D", "锯齿形"))),
    q("single_choice", "摩擦式离合器过载打滑时，摩擦消耗的功会转变为____。", "B", "clutch",
      options=opts(("A", "电能"), ("B", "热量"), ("C", "动能"), ("D", "势能"))),
    q("fill_blank", "摩擦式离合器最常见的结构形式是____摩擦离合器。", ["圆盘式"], "clutch"),

    # ================= 第十八章：弹簧 =================
    q("single_choice", "弹簧按承受载荷不同可分为压缩弹簧、拉伸弹簧、扭转弹簧和____。", "B", "spring",
      options=opts(("A", "板弹簧"), ("B", "弯曲弹簧"), ("C", "碟形弹簧"), ("D", "环形弹簧"))),
    q("true_false", "弹簧丝直径大于12mm时，碳素弹簧钢不容易淬透。", True, "spring"),
    q("single_choice", "螺旋压缩弹簧特性曲线中，Flim表示____。", "C", "spring",
      options=opts(("A", "最小工作载荷"), ("B", "最大工作载荷"), ("C", "极限载荷"), ("D", "初始载荷"))),
    q("fill_blank", "弹簧按载荷性质分为三类，其中Ⅰ类是受变载荷作用次数在____次以上或很重要的弹簧。", ["10^6"], "spring"),
    q("multiple_choice", "弹簧的功用包括____。", ["A", "B", "C", "D"], "spring",
      options=opts(("A", "缓冲吸振"), ("B", "控制运动"), ("C", "储能输出"), ("D", "测力"))),
    q("single_choice", "利用弹簧变形吸收冲击和振动能量，属于弹簧的____功用。", "B", "spring",
      options=opts(("A", "控制运动"), ("B", "缓和冲击和吸收振动"), ("C", "储存及输出能量"), ("D", "测量力的大小"))),
    q("single_choice", "弹簧秤利用弹簧变形量与载荷呈线性关系，属于弹簧的____功用。", "C", "spring",
      options=opts(("A", "控制运动"), ("B", "储能输出"), ("C", "测量力的大小"), ("D", "改变自振频率"))),
    q("true_false", "碟形弹簧和环形弹簧具有很高的缓冲吸振能力，多用于重型机械的缓冲装置。", True, "spring"),
    q("single_choice", "盘弹簧（平面涡卷弹簧）轴向尺寸很小，常用作____的储能装置。", "B", "spring",
      options=opts(("A", "车辆悬挂"), ("B", "仪器和钟表"), ("C", "重型机械缓冲"), ("D", "发动机支撑"))),
    q("single_choice", "板弹簧主要用作____的减振装置。", "B", "spring",
      options=opts(("A", "仪器仪表"), ("B", "各种车辆"), ("C", "钟表"), ("D", "安全阀"))),
    q("single_choice", "合金弹簧钢相比碳素弹簧钢，主要优势是____。", "B", "spring",
      options=opts(("A", "价格更便宜"), ("B", "适用于变载荷、冲击载荷或高温场合"), ("C", "不需要热处理"), ("D", "密度更小"))),
    q("true_false", "有初应力的拉伸弹簧，只有当工作载荷大于初拉力F0时，弹簧才开始伸长。", True, "spring"),
    q("single_choice", "弹簧特性曲线中，Fmin表示____。", "C", "spring",
      options=opts(("A", "极限载荷"), ("B", "最大工作载荷"), ("C", "预加的初始载荷（最小工作载荷）"), ("D", "平均载荷"))),
    q("single_choice", "弹簧按载荷性质分类中，基本上受静载荷的弹簧属于____。", "C", "spring",
      options=opts(("A", "Ⅰ类"), ("B", "Ⅱ类"), ("C", "Ⅲ类"), ("D", "Ⅳ类"))),
]


def main():
    for i, item in enumerate(QUESTIONS, start=1):
        item_with_id = {"id": f"ai_q_{i:04d}", "seq": i, **item}
        QUESTIONS[i - 1] = item_with_id

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(QUESTIONS, f, ensure_ascii=False, indent=2)

    from collections import Counter
    type_counter = Counter(x["type"] for x in QUESTIONS)
    kp_counter = Counter(x["knowledge_point_id"] for x in QUESTIONS)
    print(f"共生成 {len(QUESTIONS)} 题，已写入 {OUTPUT_JSON}")
    print("题型分布：", dict(type_counter))
    print("涉及知识点数：", len(kp_counter))
    print("每章覆盖情况：", dict(kp_counter))


if __name__ == "__main__":
    main()
